version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo/src
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'npm install'
     


